spring:
  datasource:
#    url: jdbc:postgresql://postgres:5432/ms
    url: jdbc:postgresql://localhost:5432/ms
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  cloud:
    stream:
      bindings:
        mailOperationInputChannel:
          destination: mail-service.operation
          group: mail-service-group
          binder: local_rabbit
      rabbit:
        bindings:
          mailOperationInputChannel:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: trendburada
                password: trendburada
                virtual-host: /
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: trendburada
#    password: trendburada
#    ssl:
#      enabled: false
#      listener:
#        simple:
#          default-requeue-rejected: false
#          retry:
#            enabled: true
#          acknowledge-mode: auto
eureka:
  client:
    service-url:
#      defaultZone: http://eureka:5555/eureka/
      defaultZone: http://localhost:5555/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

#  spring.rabbitmq.host=localhost
#  spring.rabbitmq.port=5672
#  spring.rabbitmq.username=admin
#  spring.rabbitmq.password=123456
#  rabbitmq.exchange=bilisimio.exchange
#  rabbitmq.queue=bilisimio.queue
#  rabbitmq.routingkey=bilisimio.routingkey
#  spring.main.allow-bean-definition-overriding=true

#eureka.client.service-url.defaultZone =http://localhost:5555/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.healthcheck.enabled=true
#eureka.instance.prefer-ip-address=true