spring:
  datasource:
#    url: jdbc:postgresql://postgres:5432/ms
    url: jdbc:postgresql://localhost:5432/ms
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  cloud:
    stream:
      bindings:
        mailOperationInputChannel:
          destination: mail-service.operation
          group: mail-service-group
          binder: local_rabbit
      rabbit:
        bindings:
          mailOperationInputChannel:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: trendburada1
                password: trendburada
                virtual-host: /
eureka:
  client:
    service-url:
#      defaultZone: http://eureka:5555/eureka/
      defaultZone: http://localhost:5555/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true